# Конфигурация ClanPlugin

# Настройки базы данных
database:
  # Тип БД: sqlite или mysql
  type: sqlite
  
  # Настройки для MySQL (если type: mysql)
  host: localhost
  port: 3306
  database: clans
  username: root
  password: password

# Настройки кланов
clans:
  # Минимальная длина названия
  min_name_length: 3
  # Максимальная длина названия
  max_name_length: 16
  # Минимальная длина тега
  min_tag_length: 2
  # Максимальная длина тега
  max_tag_length: 5
  # Стартовый максимум участников
  default_max_members: 10
  # Максимальный уровень клана
  max_level: 10
  # Стоимость создания клана
  creation_cost: 1000.0
  # Стоимость телепорта домой
  home_teleport_cost: 100.0
  # Задержка телепорта в секундах
  home_teleport_delay: 5

# Настройки автосохранения
autosave:
  # Интервал в минутах
  interval: 5
  # Сообщение в консоль
  log_message: false

# Настройки чата
chat:
  # Формат сообщения в клановом чате
  format: "&7[&6Клан&7] &f%player%: &e%message%"
  # Формат тега клана в обычном чате
  tag_format: "&7[&6%tag%&7] "

# Награды за убийства
pvp:
  # Награда за убийство
  kill_reward: 100.0
  # Штраф за смерть
  death_penalty: 50.0
  # Давать награду за убийство союзников
  reward_ally_kills: false

# Уровни клана
levels:
  # Стоимость повышения уровня
  upgrade_costs:
    2: 5000.0
    3: 10000.0
    4: 20000.0
    5: 35000.0
    6: 50000.0
    7: 75000.0
    8: 100000.0
    9: 150000.0
    10: 200000.0
  # Максимум участников на уровень
  max_members:
    1: 10
    2: 15
    3: 20
    4: 25
    5: 30
    6: 35
    7: 40
    8: 45
    9: 50
    10: 60

# Отладка
debug: false