# ClanPlugin Configuration
# Версия: 1.0.0

# Настройки базы данных
database:
  # Тип БД (пока только sqlite)
  type: sqlite
  # Имя файла БД
  filename: clans.db

# Настройки кланов
clans:
  # Минимальная длина имени клана
  name-min-length: 3
  # Максимальная длина имени клана
  name-max-length: 32
  # Минимальная длина тега клана
  tag-min-length: 2
  # Максимальная длина тега клана
  tag-max-length: 8
  # Начальный лимит участников
  default-max-members: 10
  # Увеличение лимита каждые N уровней
  member-increase-per-levels: 5
  # Количество добавляемых слотов
  member-increase-amount: 2

# Настройки приглашений
invites:
  # Время жизни приглашения в минутах
  expire-minutes: 5
  # Могут ли рекруты приглашать новых игроков
  recruits-can-invite: false

# Настройки опыта и уровней
experience:
  # Базовый опыт за убийство
  base-kill-exp: 10
  # Множитель опыта за убийство врага
  enemy-kill-multiplier: 2.0
  # Формула требуемого опыта: base + (level * multiplier) + (level^2 * power)
  level-requirement:
    base: 100
    multiplier: 100
    power: 10

# Настройки отображения
display:
  # Показывать теги кланов над головами
  show-tags-above-head: true
  # Показывать теги в табе
  show-tags-in-tab: true
  # Показывать теги в чате
  show-tags-in-chat: true
  # Цвета тегов по уровням клана
  tag-colors:
    0: GRAY
    5: AQUA
    10: GREEN
    20: YELLOW
    30: GOLD
    40: RED
    50: DARK_RED

# Настройки PvP
pvp:
  # Разрешить PvP между членами одного клана
  friendly-fire: false
  # Защита новичков (в секундах после вступления)
  newbie-protection: 0

# Настройки чата клана
chat:
  # Включить чат клана
  enabled: true
  # Префикс для сообщений клана
  prefix: "&7[&6CLAN&7]"
  # Формат сообщения
  format: "%prefix% &7%player%: &f%message%"

# Настройки регионов кланов
regions:
  enabled: true
  protection:
    block-break: true
    block-place: true
    container-access: true
    entity-damage: true
    messages:
      no-permission: "&cВы не можете делать это на территории %clan%"
  marker-blocks:
    COPPER_ORE:
      display-name: "Медный маркер"
      min-clan-level: 1
      max-radius: 25
    EMERALD_ORE:
      display-name: "Изумрудный маркер"
      min-clan-level: 5
      max-radius: 75

# Настройки статистики
statistics:
  # Сохранять детальную статистику
  detailed: true
  # Интервал сохранения статистики (в минутах)
  save-interval: 5

# Настройки производительности
performance:
  # Максимальное количество кланов для загрузки в топе
  max-top-clans: 10
  # Кешировать данные кланов (не рекомендуется при ограниченной RAM)
  cache-enabled: false
  # Время жизни кеша в секундах
  cache-ttl: 60

# Настройки отладки
debug:
  # Показывать SQL запросы
  show-sql: false
  # Форматировать SQL запросы
  format-sql: false
  # Включить статистику Hibernate
  statistics: false
  # Логировать все действия с кланами
  log-actions: false

# Сообщения
messages:
  # Префикс всех сообщений плагина
  prefix: "&7[&6Clans&7] "
  # Язык сообщений
  language: ru