name: ClanPlugin
version: 1.0.0
main: com.cruiser.ClanPlugin
api-version: '1.21'
author: Cruiser
description: Система кланов для Paper сервера

commands:
  clan:
    description: Основная команда для управления кланами
    usage: /<command> help
    aliases: [c, clans]
    
permissions:
  clan.use:
    description: Разрешение на использование команд клана
    default: true
  clan.admin:
    description: Административные команды кланов
    default: op
  clan.bypass.limit:
    description: Обход лимитов клана
    default: op